# Generated by Django 6.0.1 on 2026-02-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('must', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(),
        ),
    ]
