# Generated by Django 6.0.1 on 2026-02-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('must', '0002_alter_review_options_alter_review_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='content',
        ),
    ]
